# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3.8'

services:
  postgresql:
    container_name: postgres16
    image: bitnami/postgresql:latest
    networks:
      - app-tier
    ports:
      - '5432:5432'
    expose:
      - 5432      
    volumes:
      #- postgresql_data:/bitnami/postgresql # <--這是bitnami/postgresql 15.4要綁定的, 在16版起就不用了
      - .\pgsVol:/demo
    environment:
      POSTGRESQL_POSTGRES_PASSWORD: "P@ssw0rd!"
      POSTGRESQL_USERNAME: "pguser"
      POSTGRESQL_PASSWORD: "password123"
      POSTGRESQL_DATABASE: "mydb"
    healthcheck:
      interval: 5s
      timeout: 1s
      retries: 2
      start_period: 5s

  pgadmin4:
    container_name: my_pgadmin4
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "YOUR@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PASSWORD"
      PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: 365
      PGADMIN_CONFIG_MAX_SESSION_IDLE_TIME: 60
    volumes:
      - .\pgAdmVol:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgresql
    networks:
      - app-tier
    healthcheck:
      interval: 5s
      timeout: 1s
      retries: 2
      start_period: 5s

volumes:
  postgresql_data:
    driver: local

networks:
  app-tier:
    driver: bridge
    name: my_postgres_net
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1